version: '3'

services:
  local-spark:
    image: local-spark
    container_name: local-spark
    build:
      context: ./
      dockerfile: ./containers/spark/Dockerfile
    environment:
      METADATA_DRIVERNAME: postgresql
      METADATA_HOST: metadata
      METADATA_PORT: '5432'
      METADATA_USERNAME: tris
      METADATA_PASSWORD: tris123
      METADATA_DATABASE: metadata
    volumes:
      - ./src:/opt/spark/work-dir/src
  
  metadata:
    image: postgres:15
    hostname: metadata
    container_name: metadata
    environment:
      POSTGRES_USER: tris
      POSTGRES_PASSWORD: tris123
      POSTGRES_DB: metadatadb
    ports:
      - "5432:5432"


  minio:
    image: 'minio/minio:RELEASE.2023-07-21T21-12-44Z'
    hostname: minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
  
  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add minio http://minio:9000 minio minio123; /usr/bin/mc rm -r --force minio/marketing_project; /usr/bin/mc mb minio/marketing_project; /usr/bin/mc policy download minio/marketing_project; exit 0; "


